language: rust
os:
    - linux
    - osx
script:
    - (cd cargo/fizzbuzz && cargo build -v)
    - (cd cargo/brainfuck && cargo build -v)
    - (cd cargo/project-euler && cargo build -v && cargo test -v)
